### PR TITLE
Fix missing lessons

### LINKED ISSUE #20: Timetables missing lessons
Test precisely how timetables work and fix it that it not always shows up correct lessons.

/cc @DarkMuffinJoe

### PR DESCRIPTION
**Pull request by JakubBizewski**
Fix to issue #20

### CODE REVIEW

File: src/tiles/TimetableTile.vue [hunk 1]
```diff
@@ -90,20 +90,27 @@
...
-                    if (key == 1 && now.diff(lesson.time[0]) < 0)
+                function shouldStartPicking(lesson, key, keyValues) {
+                    if (key == keyValues.lowest && now.diff(lesson.time[0]) < 0)
                         return true
 
                     if (now.diff(lesson.time[0], 'minutes') <= 45)
                         return true
 
-                    if (key == (length - 2))
+                    if (key == (keyValues.highest - 2))
```
Comment (Albert221) [inline src/tiles/TimetableTile.vue]: These parenthesizes are redundant.

**Review by Albert221 — APPROVED** [review]
One minor CS thing, good work :beers:
